on:
  pull_request:  

name: Review Workflow

jobs:
  review:
    name: Review
    runs-on: ubuntu-latest
    steps:
      # prepare env
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      # check
      - name: Install
        run: bun install

      - name: Build
        run: bun run build
